### ISSUE TITLE
在公众号文章中插入Gitter小程序后点击进入一直在加载中

### ISSUE THREAD

**Issue by LiarrDev** [huangjianke/Gitter#52]
已在文章中配置页面的对应路径，但是打开后一直在加载无法正常进入

![image](https://user-images.githubusercontent.com/40908569/66268144-ece42f00-e86c-11e9-8485-13baf4e40734.png)

但是直接从小程序进入对应的页面却没有问题

**Comment by huangjianke** [comment]
配置的页面路径是什么

**Comment by LiarrDev** [comment]
根据微信的提示，到小程序内复制的页面路径，比如获取 Gitter 的路径：

```
pages/repo/repo.html?url=https%3A%2F%2Fapi.github.com%2Frepos%2Fhuangjianke%2FGitter&__key_=15703672762713
```

**Comment by LiarrDev** [comment]
> 配置的页面路径是什么

根据微信的提示，到小程序内复制的页面路径，比如获取 Gitter 的路径：

```
pages/repo/repo.html?url=https%3A%2F%2Fapi.github.com%2Frepos%2Fhuangjianke%2FGitter&__key_=15703672762713
```

**Comment by huangjianke** [comment]
路径参数不传，或者传
pages/index/index 试试




            
            
                
                    
                            
                                
                            
                            
                                huang jianke
                            
                    
                        
                            
                                    邮箱：huangjianke00@gmail.com
                            
                        
                
            
        


在2019年10月06日 21:14，Liarr 写道： 
配置的页面路径是什么

根据微信的提示，到小程序内复制的页面路径，比如获取 Gitter 的路径：
pages/repo/repo.html?url=https%3A%2F%2Fapi.github.com%2Frepos%2Fhuangjianke%2FGitter&__key_=15703672762713



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/huangjianke/Gitter/issues/52?email_source=notifications\u0026email_token=ACCKFZZOUEQ5I7CUSJ3Q4V3QNHQEHA5CNFSM4I53RLRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAOJ2JY#issuecomment-538746151",
"url": "https://github.com/huangjianke/Gitter/issues/52?email_source=notifications\u0026email_token=ACCKFZZOUEQ5I7CUSJ3Q4V3QNHQEHA5CNFSM4I53RLRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAOJ2JY#issuecomment-538746151",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by LiarrDev** [comment]
> 路径参数不传，或者传 pages/index/index 试试 huang jianke 邮箱：huangjianke00@gmail.com 在2019年10月06日 21:14，Liarr 写道： 配置的页面路径是什么 根据微信的提示，到小程序内复制的页面路径，比如获取 Gitter 的路径： pages/repo/repo.html?url=https%3A%2F%2Fapi.github.com%2Frepos%2Fhuangjianke%2FGitter&__key_=15703672762713 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#52?email_source=notifications\u0026email_token=ACCKFZZOUEQ5I7CUSJ3Q4V3QNHQEHA5CNFSM4I53RLRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAOJ2JY#issuecomment-538746151", "url": "#52?email_source=notifications\u0026email_token=ACCKFZZOUEQ5I7CUSJ3Q4V3QNHQEHA5CNFSM4I53RLRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAOJ2JY#issuecomment-538746151", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

`pages/index/index` 是小程序主页的路径，我想插入具体某个 repo 的路径，让用户点击后可以打开小程序，并跳转到对应的 repo 中

**Comment by huangjianke** [comment]
用这种格式：
`/pages/repo/repo?url=https://api.github.com/repos/huangjianke/Gitter`
 这部分是固定的：
`/pages/repo/repo?url=https://api.github.com/repos/`

**Comment by LiarrDev** [comment]
> 用这种格式：
> `/pages/repo/repo?url=https://api.github.com/repos/huangjianke/Gitter`
> 这部分是固定的：
> `/pages/repo/repo?url=https://api.github.com/repos/`
> 
> `https://api.github.com/repos/huangjianke/Gitter` 这部分 encodeURI

用你提供的格式可以正常打开，之前配置的路径应该是微信生成 URL 时没有生成正确的路径
